version: 0.2
env:
  parameter-store:
    DOCKER_HUB_USER: "/Test/DockerHub/User"
    DOCKER_HUB_PASS: "/Test/DockerHub/Pass"
    GITHUB_USER: "/Test/Git/User"
    GITHUB_PASS: "/Test/Git/Pass"
phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      # make a default directory that is required for the manager to start up. Normally this is handled by the install
      # tools.
      - mkdir -p /root/lightning-node

        # Copy the YMLs into the container
      - mkdir /warhouse
      - git clone https://$GITHUB_USER:$GITHUB_PASS@github.com/Casa/home-compute-warehouse --depth 1 /warehouse
      - cp /warehouse/lightning-node/*.yml ./resources

      - echo Installing source NPM dependencies...
      - npm install
  install:
    commands:
      # CodePipeline creates artifacts using zip format, which does not preserve the permissions/modes.
      # we must reset permissions here
      - chmod 755 pre-commit qemu-arm-static
  build:
    commands:
      - echo Running tests
      - npm test

      - echo Building the Docker image ...

      # building
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - docker build . -f $DOCKERFILE -t $ORGANIZATION/$REPOSITORY:$TAG
      - docker tag $ORGANIZATION/$REPOSITORY:$TAG $ORGANIZATION/$REPOSITORY:$TAG

      # push image to docker
      - echo $CODEBUILD_SOURCE_VERSION
      - if git rev-parse master|grep $CODEBUILD_SOURCE_VERSION; then docker login --username=$DOCKER_HUB_USER --password=$DOCKER_HUB_PASS; fi
      - if git rev-parse master|grep $CODEBUILD_SOURCE_VERSION; then docker push $ORGANIZATION/$REPOSITORY:$TAG; fi
  post_build:
    commands:
      - echo Build completed on `date`
