version: 0.2
env:
  parameter-store:
    DOCKER_HUB_USER: "/Test/DockerHub/User"
    DOCKER_HUB_PASS: "/Test/DockerHub/Pass"
phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Running tests
      - npm test

      - echo Building the Docker image ...

      # building x86
      - docker build . -t $ORGANIZATION/$REPOSITORY:x86
      - docker tag $ORGANIZATION/$REPOSITORY:x86 $ORGANIZATION/$REPOSITORY:x86

      # building arm
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - docker build . -f Dockerfile.armhf -t $ORGANIZATION/$REPOSITORY:arm
      - docker tag $ORGANIZATION/$REPOSITORY:arm $ORGANIZATION/$REPOSITORY:arm

      # push image to docker
      - docker login --username=$DOCKER_HUB_USER --password=$DOCKER_HUB_PASS
      - docker push $ORGANIZATION/$REPOSITORY:x86
      - docker push $ORGANIZATION/$REPOSITORY:arm
  post_build:
    commands:
      - echo Build completed on `date`