version: '2.4'

services:
  manager:
    container_name: manager
    hostname: manager
    restart: always
    image: casanode${REPOSITORY_ADDENDUM}/manager:${TAG}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /usr/local/casa/applications:/usr/local/casa/applications
      - /usr/local/casa:/usr/local/casa
      - applications_accounts:/accounts
      - settings:/settings
      # Tor volume data is created by the manager. This is to guarantee it exists before composing Bitcoind and Lnd.
      # Tor is optional for Bitcoind and Lnd, however docker still requires the volume exist.
      # This volume can be removed after Lnd can use Tor passwords. Bitcoind already accepts Tor passwords.
      - tor-cookie:/root/.tor/:ro
      - tor-hidden-services:/var/lib/tor/
    ports:
      - "3000:3000"
    environment:
      - DEVICE_HOST
      - CASABUILDER_PASSWORD
      - CASAWORKER_PASSWORD
      - DISABLE_YML_UPDATE
      - SYSTEM_USER
      - TAG
    network_mode: host
    labels:
      - casa=persist
    mem_limit: 256m
    memswap_limit: -1 # unlimited access to device swap
    oom_kill_disable: true

volumes:
  settings:
  applications_accounts:
    external: true
  tor-cookie: # remove this volume after lnd can use tor passwords
  tor-hidden-services:
