version: '2.4'

services:
  bitcoind:
    container_name: bitcoind
    hostname: bitcoind
    restart: unless-stopped
    image: casacomputer/bitcoind:${TAG}
    ports:
      - "12000:12000"
      - "12001:12001"
      - "28332:28332"
    entrypoint: ./chains/bitcoind/start_bitcoind.sh
    volumes:
      - bitcoind-data:/usr/local/casa/chains/bitcoind/data
      - rpc:/usr/local/casa/chains/bitcoind/rpc
    networks:
       - arpanet
    environment:
      - BITCOIN_NETWORK
      - BITCOIND_LISTEN
    mem_limit: 512m
    memswap_limit: -1 # unlimited access to device swap
    cpus: 3 #bitcoind_cpus
    cpuset: 1-3 #bitcoind_cpuset

  lnapi:
    container_name: lnapi
    hostname: lnapi
    restart: unless-stopped
    image: casacomputer/lnapi:${TAG}
    ports:
      - "3002:3000"
    volumes:
      - rpc:/rpc:ro
      - lnd-data:/lnd:ro
      - channel-data:/channel-data
    networks:
      - arpanet
    environment:
      - BITCOIN_NETWORK
      - BITCOIND_HOST
      - BITCOIND_RPC_PORT
      - COOKIE_FILE
      - ENVIRONMENT
      - JWT_EXPIRATION
      - LND_HOST
      - LND_NETWORK
      - LND_PORT
      - PROTO_FILE
      - SHARED_JWT_SECRET
      - SYSTEM_USER
      - TLS_FILE
      - USER_PASSWORD_FILE

  lnd:
    container_name: lnd
    hostname: lnd
    restart: unless-stopped
    image: casacomputer/lnd:${TAG}
    ports:
      - "9735:9735"
      - "10009:10009"
    depends_on:
      - bitcoind
    entrypoint: ./chains/lnd/start-lnd.sh
    networks:
      - arpanet
    volumes:
      - lnd-data:/root/.lnd #TODO: split up data, config
      - rpc:/usr/local/casa/chains/bitcoind/rpc:ro
    environment:
      - AUTOPILOT
      - BACKEND
      - CHAIN
      - LND_NETWORK
      - LND_NODE_ALIAS
      - MAX_CHANNELS
      - MAX_CHAN_SIZE
      - OPEN_CHAN_FEE_RATE
    cpus: 3 #lnd_cpus
    cpuset: 1-3 #lnd_cpuset

  space-fleet:
    container_name: space-fleet
    hostname: space-fleet
    restart: unless-stopped
    image: casacomputer/space-fleet:${TAG}
    ports:
      - "80:3000"
    networks:
      - arpanet
    environment:
      - DEVICE_HOST
    mem_limit: 256m
    memswap_limit: -1 # unlimited access to device swap
    oom_kill_disable: true

volumes:
  channel-data:
  bitcoind-data:
  lnd-data:
  rpc:

networks:
  arpanet:
